// module.exports = function (router) {
	// // START__####################################################################################################
	//
	// Add content key/value pairs here
	// Add content key/value pairs here
	// Content variables are isted in the same order as folders when sorted a-z
	// If a variable has been defined in a previous file it is not defined again
	// Comments sepperate the list
	// This list should be moved in to it's own file in the future
	module.exports = {
	    addressLine1Label: 'Building and street <span class="govuk-visually-hidden">line 1 of 2</span>',
	    addressLine2Label: '<span class="govuk-visually-hidden">Building and street line 2 of 2</span>',
	    addressPostcodeLabel: 'Postcode',
	    addressPostcodeOptionalLabel: 'Postcode (optional)',
	    addressQuestion: 'Enter your address',
	    britishCitizenQuestion: 'Are you a British citizen?',
	    compensationWhyNotQuestion: "Why did you not apply for compensation from another source?",
	    countyLabel: 'County (optional)',
	    crimeReferenceNumberHint: 'This is the reference number the police gave the crime when it was reported.',
	    crimeReferenceNumberQuestion: 'What\'s the crime reference number?',
	    crimeReferenceNumberQuestionCA: 'Crime reference number?',
			crimeReferenceError: 'Enter the crime reference number',
	    crimeReportedDateHint: 'For example, 31 3 2018. You can enter an approximate date',
	    crimeReportedDateQuestion: 'When was the crime reported to police?',
	    dateOfBirthQuestion: "Enter your date of birth",
	    declarationBody: 'By continuing you confirm that the information you will give is true as far as you know.',
	    declarationHeading: 'Declaration',
	    doYouKnowOffenderQuestion: "Do you know the name of the offender?",
	    doYouKnowOffenderHint: "We will not contact them.",
	    emailAddressError: "Enter your email address, for example john.smith@email.com",
	    emailAddressErrorSubHeader: "Enter your email address?",
	    emailAddressHint: "We'll use this to contact you about your application for example, to request more information and tell you about our decision",
	    emailAddressQuestion: "Enter your email address",
	    errorBeforeIncident: "Your date of birth must be before the crime happened",
	    errorIncompleteMessage: "Enter your date of birth and include a day, month and year",
	    errorMessageContent: 'Select Once or Over a period of time',
	    errorMessageTitle: 'There is a problem',
	    errorPastMessage: "Your date of birth must be in the past",
	    howMuchCompensationHint: 'You can also tell us if you are still waiting to find out.',
	    howMuchCompensationQuestion: 'How much compensation did you get?',
			impactHeading: 'Impact of the crime on you',
	    incidentDateHeading: "When did the crime happen?",
	    incidentDateHint: 'For example, 31 3 2018. You can enter an approximate date ',
	    incidentLocationHeading: "Where did the crime happen?",
			incidentLocationReveal: "Enter the town or location",
			incidentLocationRevealOther: "Enter the location",
	    incidentReportedQuestion: 'Was the crime reported to the police?',
			incidentReportedError: "Select yes if the crime was reported to the police",
	    itemOneValue: 'Once',
	    itemTwoValue: 'Over a period of time',
      locationTownQuestion: 'Enter more details about where the crime happened',
	    nameErrorNoFirstName: "Enter your first name",
	    nameErrorNoLastName: "Enter your last name",
	    nameErrorNoTitle: "Enter your title",
	    nameOtherError: "Select yes if you have been known by any other names",
	    nameOtherQuestion: 'Have you ever been known by any other names?',
	    nameOtherWhatQuestion: "What other names have you used?",
	    nameQuestion: 'Enter your name',
	    nameTitleField: 'Title',
	    nameFirstNameField: 'First name',
	    nameLastNameField: 'Last name',
	    offenderNameQuestion: 'Enter their name',
	    offenderNameQuestionCA: 'Offenders name',
	    ongoingRelationshipQuestion: "Have you have any contact with this person since the incident?",
	    ongoingRelationshipHint: "We will not pay compensation if the offender could benefit from it.",
	    otherCompensationHint: 'Other sources of compensation include, for example, insurance claims, civil damages and compensation issued by a court.',
	    otherCompensationQuestion: 'Have you applied anywhere else for compensation for this crime?',
			compYesWhoHint:'Who did you apply to?',
			compYesAmountHint:'How much did you receive?',
			compWaitingHint: 'Who did you apply to?',
			compNoHint: 'Briefly explain why not.',
	    over18Question: 'Are you 18 or over?',
			over18errorGuidance: 'Select yes if you are over 18',
	    periodOfAbuseEndQuestion: 'When did it stop?',
	    periodOfAbuseHint: 'For example, 03 2018. You can enter an approximate date',
	    periodOfAbuseStartQuestion: 'When did it start?',
	    phoneNumberHint: "We'll use this to contact you about your application for example, to request more information",
	    phoneNumberQuestion: "Enter your telephone number",
	    policeForceHint: "Enter the police force name, for example, Humberside police.",
	    policeForceQuestion: 'Was the crime reported to Police Scotland Greater Glasgow?',
      policeForceManualQuestion: 'What force was the crime reported to?',
	    previousApplicationsQuestion: 'Have you applied for compensation from us for this crime before?',
	    reportingDelayQuestion: "Select a reason for the delay in reporting the crime to the police",
			sameFamilyQuestion: 'Were you and the offender living together as family at the time?',
			sameFamilyError: 'Select yes if you and the offender were living together as family when the crime happened',
	    selectAddressLable: 'Select an address',
	    sexualAbuseQuestion: 'Were you a victim of sexual assault or abuse?',
			sexualAbuseError: 'Select yes if you were a victim of sexual assault or abuse',
	    singleOrMultipleIncidentsQuestion: 'Did the crime happen once or over a period of time?',
	    townOrCityLabel: 'Town or city',
			transitionHeading: 'You are being redirected to our other application site',
	    warningText: "If you deliberately give false or misleading information, you may get less compensation or be prosecuted.",
	    whatIsRelationshipQuestion: "If you have contact with the offender, describe it below",
	    whoCompensationQuestion: 'Who else have you applied to for compensation?',
	    whoIsMakingTheApplicationQuestion: 'Who are you applying for?',
			whoIsMakingTheApplicationError: 'Select Myself if you are the person applying for compensation',
	    whyDelayQuestion: 'Select a reason for the delay in making your application',
			reportedDateErrorPast: 'The date the crime was reported to the police must be in the past',
			reportedDateIncompleteError: 'Enter the date the crime was reported to the police and include a day, month and year',
			reportedDateErrorBlank: 'Enter the date the crime was reported to the police',
			yourChoicesHeading: 'Select the option that applies to you',
			notEligibleHeading: 'You can not get compensation',
	};
	// // END__######################################################################################################
	// }
